### ISSUE TITLE
Does the theme support expanding and collapsing of nodes?

### ISSUE THREAD

**Issue by joel-zutobi** [grovertb/react-sortable-tree-theme-material-ui#1]
None of the pictures seem to show a + or - sign indicating that the theme supports expanding and collapsing of nodes. Are all nodes always expanded?

**Comment by grovertb** [comment]
Sorry use prop  
```js
<SortableTree
...
treeData={toggleExpandedForAll({ treeData: footerSections })} 
/>
```
or your objects must have key expanded in true

**Comment by joel-zutobi** [comment]
@grovertb 

So this means that nodes must always be expanded? Or can nodes be collapsed (with a button to expand them)?

**Comment by grovertb** [comment]
@Lewom At this time it is not possible, but i can work on it.

**Comment by joel-zutobi** [comment]
@grovertb It would be greatly appreciated. Thank you.
